import {initDatabase,filterEntities,loadEntity,findClassFeatures,findSubclassFeatures,getRecordArrays,stats,manifestEntries} from "./database.js";
import {ABILITIES,ABILITY_NAMES,SKILLS,mod,fmt,proficiency,hpAverage,abilityKey,spellDc,spellAttack,parseProgression} from "./rules.js";
import {saveCharacter,loadCharacter,clearCharacter,downloadCharacter,readCharacterFile} from "./storage.js";

const $=id=>document.getElementById(id);let character, refs={class:null,subclass:null,race:null,background:null}, details={};
const fresh=()=>({schema:4,name:"",level:1,xp:0,inspiration:0,edition:"2024",content:"all",classId:"",subclassId:"",raceId:"",backgroundId:"",scores:{str:10,dex:10,con:10,int:10,wis:10,cha:10},saveProficiencies:[],skillProficiencies:[],skillExpertise:[],hpCurrent:null,hpTemp:0,ac:null,speed:"",attacks:[]});
const hb=x=>!!(x?.homebrew||x?.isHomebrew||x?.brew||x?.sourceCategory==="homebrew");
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const toast=t=>{const e=$("toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2000)};
const list=t=>filterEntities(t,character.edition,character.content);
const byId=id=>manifestEntries().find(x=>x.id===id)||null;
function fill(sel,items,ph){sel.innerHTML=`<option value="">${ph}</option>`;for(const [label,arr] of [["Oficial",items.filter(x=>!hb(x))],["Homebrew",items.filter(hb)]]){if(!arr.length)continue;const g=document.createElement("optgroup");g.label=label;arr.forEach(x=>{const o=document.createElement("option");o.value=x.id;o.textContent=x.name||x.id;g.appendChild(o)});sel.appendChild(g)}}
async function selectData(e){return e?await loadEntity(e):null}
function classMatches(x,c){if(!c)return false;const s=String(x.className||x.class||x.classSource||"").toLowerCase();return !s||s===String(c.name||"").toLowerCase()||s.includes(String(c.name||"").toLowerCase())}
async function refreshSelectors(){
 const cs=list("class"),rs=list("race"),bs=list("background");fill($("class"),cs,"Escolha…");fill($("race"),rs,"Escolha…");fill($("background"),bs,"Escolha…");
 $("class").value=cs.some(x=>x.id===character.classId)?character.classId:"";$("race").value=rs.some(x=>x.id===character.raceId)?character.raceId:"";$("background").value=bs.some(x=>x.id===character.backgroundId)?character.backgroundId:"";
 refs.class=byId(character.classId);let subs=list("subclass");if(refs.class)subs=subs.filter(x=>classMatches(x,refs.class));fill($("subclass"),subs,refs.class?"Escolha…":"Escolha a classe…");$("subclass").value=subs.some(x=>x.id===character.subclassId)?character.subclassId:"";
 refs.subclass=byId(character.subclassId);refs.race=byId(character.raceId);refs.background=byId(character.backgroundId);
 details.class=await selectData(refs.class);details.subclass=await selectData(refs.subclass);details.race=await selectData(refs.race);details.background=await selectData(refs.background);
}
function ability(a){return mod(character.scores[a])}
function skill(id,a){let v=ability(a),p=proficiency(character.level);if(character.skillProficiencies.includes(id))v+=p;if(character.skillExpertise.includes(id))v+=p;return v}
function classInfo(){return details.class?.class?.[0]||details.class?.["class"]?.[0]||details.class||{}}
function subclassInfo(){return details.subclass?.subclass?.[0]||details.subclass?.["subclass"]?.[0]||details.subclass||{}}
function raceInfo(){return details.race?.race?.[0]||details.race?.["race"]?.[0]||details.race||{}}
function faces(){return Number(classInfo().hd?.faces||classInfo().hitDie?.faces||8)||8}
function spellAbility(){return abilityKey(classInfo().spellcastingAbility||classInfo().spellcasting?.ability)}
function calc(){const c=classInfo(),pb=proficiency(character.level),f=faces(),hp=Math.max(1,f+ability("con")+(character.level-1)*(hpAverage(f)+ability("con"))),sa=spellAbility(),sm=sa?ability(sa):0;return{pb,f,hp,initiative:ability("dex"),ac:character.ac??10+ability("dex"),passive:10+skill("perception","wis"),speed:character.speed||raceInfo().speed||"30 ft",spellAbility:sa,spellDc:sa?spellDc(pb,sm):null,spellAttack:sa?spellAttack(pb,sm):null}}
function renderAbilities(){$("attributes").innerHTML=ABILITIES.map(a=>`<div class="ability"><h3>${ABILITY_NAMES[a]}</h3><input data-ab="${a}" type="number" min="1" max="30" value="${character.scores[a]}"><div class="mod">${fmt(ability(a))}</div></div>`).join("");document.querySelectorAll("[data-ab]").forEach(e=>e.oninput=()=>{character.scores[e.dataset.ab]=Number(e.value)||0;renderAll()})}
function renderSaves(){const p=proficiency(character.level);$("saves").innerHTML=ABILITIES.map(a=>`<label class="skill"><input data-save="${a}" type="checkbox" ${character.saveProficiencies.includes(a)?"checked":""}><span>${ABILITY_NAMES[a]}</span><strong>${fmt(ability(a)+(character.saveProficiencies.includes(a)?p:0))}</strong></label>`).join("");document.querySelectorAll("[data-save]").forEach(e=>e.onchange=()=>{const a=e.dataset.save;character.saveProficiencies=e.checked?[...new Set([...character.saveProficiencies,a])]:character.saveProficiencies.filter(x=>x!==a);renderAll()})}
function renderSkills(){$("skills").innerHTML=SKILLS.map(([id,n,a])=>`<label class="skill"><input data-skill="${id}" type="checkbox" ${character.skillProficiencies.includes(id)?"checked":""}><span>${n} <small>${a.toUpperCase()}</small></span><strong>${fmt(skill(id,a))}</strong></label>`).join("");document.querySelectorAll("[data-skill]").forEach(e=>e.onchange=()=>{const id=e.dataset.skill;character.skillProficiencies=e.checked?[...new Set([...character.skillProficiencies,id])]:character.skillProficiencies.filter(x=>x!==id);renderAll()})}
function renderCombat(){const c=calc();$("pb").textContent=fmt(c.pb);$("hp").textContent=c.hp;$("hit-die").textContent=`d${c.f}`;$("ac").textContent=c.ac;$("initiative").textContent=fmt(c.initiative);$("passive").textContent=c.passive;$("speed").textContent=c.speed;$("spell-dc").textContent=c.spellDc??"—";$("spell-attack").textContent=c.spellAttack==null?"—":fmt(c.spellAttack);$("hp-current").value=character.hpCurrent??c.hp;$("hp-temp").value=character.hpTemp;$("ac-input").value=c.ac;$("speed-input").value=character.speed||""}
function renderAttacks(){let a=character.attacks.length?character.attacks:[{name:"",bonus:"",damage:""}];$("attacks").innerHTML=a.map((x,i)=>`<div class="attack-row"><input data-ai="${i}" data-k="name" value="${esc(x.name)}" placeholder="Ataque"><input data-ai="${i}" data-k="bonus" value="${esc(x.bonus)}" placeholder="Bônus"><input data-ai="${i}" data-k="damage" value="${esc(x.damage)}" placeholder="Dano"><button data-del="${i}">×</button></div>`).join("")+`<button id="add-attack">Adicionar ataque</button>`;document.querySelectorAll("[data-ai]").forEach(e=>e.oninput=()=>{const i=+e.dataset.ai;character.attacks[i]??={};character.attacks[i][e.dataset.k]=e.value});document.querySelectorAll("[data-del]").forEach(e=>e.onclick=()=>{character.attacks.splice(+e.dataset.del,1);renderAttacks()});$("add-attack").onclick=()=>{character.attacks.push({name:"",bonus:"",damage:""});renderAttacks()}}
function renderSpells(){const q=$("spell-search").value.toLowerCase(),lv=$("spell-level-filter").value;const l=list("spell").filter(x=>(!q||String(x.name).toLowerCase().includes(q))&&(lv==="all"||String(x.level??0)===lv)).slice(0,500);$("spells").innerHTML=l.length?l.map(x=>`<article class="spell"><h3>${esc(x.name)}${hb(x)?' <span class="badge">Homebrew</span>':""}</h3><small>${x.level===0?"Truque":`${x.level||0}º nível`} · ${esc(x.source||"")}</small></article>`).join(""):"<p>Nenhuma magia encontrada.</p>"}
function text(v){const out=[];const w=x=>{if(typeof x==="string")out.push(x);else if(Array.isArray(x))x.forEach(w);else if(x&&typeof x==="object"){if(x.entries)w(x.entries);else if(x.entry)w(x.entry)}};w(v);return out.slice(0,40).join(" ")}
async function renderProgression(){
 const cf=refs.class?await findClassFeatures(refs.class,character.level):[],sf=refs.subclass?await findSubclassFeatures(refs.subclass,character.level):[];
 const map=new Map();[...cf,...sf].forEach(f=>{const l=Number(f.level||1);if(!map.has(l))map.set(l,[]);map.get(l).push(f)});
 $("progression").innerHTML=Array.from({length:character.level},(_,i)=>i+1).map(l=>{const fs=map.get(l)||[];return `<div class="progress-card"><h3>Nível ${l}${l===character.level?" · atual":""}</h3>${fs.length?fs.map(f=>`<div class="feature-level"><span class="lvl">${f.__type==="subclassFeature"?"SC":"CL"}</span><div><strong>${esc(f.name||"Característica")}</strong><p>${esc(text(f.entries)||"Característica desbloqueada.")}</p></div></div>`).join(""):"<p class='muted'>Sem característica estruturada encontrada no banco.</p>"}</div>`}).join("");
 const c=classInfo(),prog=c.casterProgression||c.casterProgressionByLevel, slots=c.spellcasting?.slots||c.spellSlots;
 $("spell-progression").innerHTML=prog?`<p>Progressão de conjuração: <strong>${esc(prog)}</strong></p>`:"<p class='muted'>A classe selecionada não expõe progressão de conjuração estruturada.</p>";
}
async function renderDetails(){const vals=[refs.race,refs.class,refs.subclass,refs.background].filter(Boolean);$("selection-details").innerHTML=vals.map(x=>`<p><strong>${esc(x.name)}</strong> <span class="muted">· ${hb(x)?"Homebrew":"Oficial"} · ${esc(x.source||"")}</span></p>`).join("")||"<p>Escolha suas opções.</p>";const s=stats();$("selection-note").textContent=`Banco: ${s.entities} registros · ${s.official} oficiais · ${s.homebrew} Homebrew`}
async function renderAll(){renderAbilities();renderSaves();renderSkills();renderCombat();renderAttacks();renderSpells();await renderDetails();await renderProgression()}
async function sync(){await refreshSelectors();$("edition").value=character.edition;$("content").value=character.content;$("name").value=character.name;$("level").value=character.level;$("xp").value=character.xp;$("inspiration").value=character.inspiration;await renderAll()}
function wire(){
 $("edition").onchange=async e=>{character.edition=e.target.value;character.classId=character.subclassId=character.raceId=character.backgroundId="";await sync()};$("content").onchange=async e=>{character.content=e.target.value;await sync()};
 $("class").onchange=async e=>{character.classId=e.target.value;character.subclassId="";await sync()};$("subclass").onchange=async e=>{character.subclassId=e.target.value;await sync()};$("race").onchange=async e=>{character.raceId=e.target.value;await sync()};$("background").onchange=async e=>{character.backgroundId=e.target.value;await sync()};
 $("name").oninput=e=>character.name=e.target.value;$("level").oninput=async e=>{character.level=Math.max(1,Math.min(20,+e.target.value||1));await renderAll()};$("xp").oninput=e=>character.xp=+e.target.value||0;$("inspiration").oninput=e=>character.inspiration=+e.target.value||0;
 $("hp-current").oninput=e=>character.hpCurrent=+e.target.value||0;$("hp-temp").oninput=e=>character.hpTemp=+e.target.value||0;$("ac-input").oninput=e=>{character.ac=+e.target.value||0;renderCombat()};$("speed-input").oninput=e=>character.speed=e.target.value;
 $("spell-search").oninput=renderSpells;$("spell-level-filter").onchange=renderSpells;
 document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tab-panel").forEach(x=>x.classList.remove("active"));t.classList.add("active");$(`tab-${t.dataset.tab}`).classList.add("active")});
 $("save-character").onclick=()=>{saveCharacter(character);toast("Personagem salvo.")};$("export-character").onclick=()=>downloadCharacter(character);
 $("new-character").onclick=async()=>{if(confirm("Criar novo personagem?")){clearCharacter();character=fresh();await sync();toast("Novo personagem.")}};
 $("import-character").onchange=async e=>{try{character={...fresh(),...(await readCharacterFile(e.target.files[0]))};character.scores={...fresh().scores,...character.scores};await sync();toast("Importado.")}catch{toast("JSON inválido.")}e.target.value=""}
}
(async()=>{try{await initDatabase();const s=stats();$("db-status").textContent=`Banco carregado · ${s.entities} registros`;character=loadCharacter()||fresh();wire();await sync()}catch(e){console.error(e);$("db-status").textContent="Erro no banco";$("selection-note").textContent=e?.message||"Não foi possível ler data/manifest.json."}})();
